# Generated by Django 3.1 on 2020-08-12 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_auto_20200811_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_catalogos', to='catalogos.catalogo'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='fabricante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens_fabricantes', to='catalogos.fabricante'),
        ),
    ]
