# Generated by Django 3.1.1 on 2020-10-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_auto_20200812_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
    ]
