# Generated by Django 3.1.2 on 2020-12-20 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0004_imagem_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='user_likes',
            field=models.ManyToManyField(related_name='imagens_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('already_liked', models.BooleanField(default=False)),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Imagem', to='catalogos.imagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
