# Generated by Django 3.1.2 on 2020-12-20 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0005_auto_20201219_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='likes',
        ),
        migrations.AlterField(
            model_name='imagem',
            name='user_likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
