# Generated by Django 3.0.3 on 2020-02-28 20:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Albuns',
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='img/imagens')),
                ('descricao', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('data_publicacao', models.DateField(default=datetime.datetime.now)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albuns.Album')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
    ]
