# Generated by Django 3.0.5 on 2020-06-01 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabricantes', '0001_initial'),
        ('albuns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='fabricante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fabricantes.Fabricante'),
        ),
    ]
